// <auto-generated />
namespace Modelos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class usuario_activo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usuario_activo));
        
        string IMigrationMetadata.Id
        {
            get { return "202112210958222_usuario_activo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
